/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as KgtRouteImport } from './routes/kgt'
import { Route as MarketplacesRouteImport } from './routes/marketplaces'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as WmsRouteImport } from './routes/wms'
import { Route as ApiBitrixLeadRouteImport } from './routes/api.bitrix-lead'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const KgtRoute = KgtRouteImport.update({
  id: '/kgt',
  path: '/kgt',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplacesRoute = MarketplacesRouteImport.update({
  id: '/marketplaces',
  path: '/marketplaces',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsRoute = WmsRouteImport.update({
  id: '/wms',
  path: '/wms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBitrixLeadRoute = ApiBitrixLeadRouteImport.update({
  id: '/api/bitrix-lead',
  path: '/api/bitrix-lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/ecommerce': typeof EcommerceRoute
  '/faq': typeof FaqRoute
  '/kgt': typeof KgtRoute
  '/marketplaces': typeof MarketplacesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/thank-you': typeof ThankYouRoute
  '/wms': typeof WmsRoute
  '/api/bitrix-lead': typeof ApiBitrixLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/ecommerce': typeof EcommerceRoute
  '/faq': typeof FaqRoute
  '/kgt': typeof KgtRoute
  '/marketplaces': typeof MarketplacesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/thank-you': typeof ThankYouRoute
  '/wms': typeof WmsRoute
  '/api/bitrix-lead': typeof ApiBitrixLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/ecommerce': typeof EcommerceRoute
  '/faq': typeof FaqRoute
  '/kgt': typeof KgtRoute
  '/marketplaces': typeof MarketplacesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/thank-you': typeof ThankYouRoute
  '/wms': typeof WmsRoute
  '/api/bitrix-lead': typeof ApiBitrixLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contacts'
    | '/ecommerce'
    | '/faq'
    | '/kgt'
    | '/marketplaces'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/thank-you'
    | '/wms'
    | '/api/bitrix-lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contacts'
    | '/ecommerce'
    | '/faq'
    | '/kgt'
    | '/marketplaces'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/thank-you'
    | '/wms'
    | '/api/bitrix-lead'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contacts'
    | '/ecommerce'
    | '/faq'
    | '/kgt'
    | '/marketplaces'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/thank-you'
    | '/wms'
    | '/api/bitrix-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactsRoute: typeof ContactsRoute
  EcommerceRoute: typeof EcommerceRoute
  FaqRoute: typeof FaqRoute
  KgtRoute: typeof KgtRoute
  MarketplacesRoute: typeof MarketplacesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  ThankYouRoute: typeof ThankYouRoute
  WmsRoute: typeof WmsRoute
  ApiBitrixLeadRoute: typeof ApiBitrixLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kgt': {
      id: '/kgt'
      path: '/kgt'
      fullPath: '/kgt'
      preLoaderRoute: typeof KgtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplaces': {
      id: '/marketplaces'
      path: '/marketplaces'
      fullPath: '/marketplaces'
      preLoaderRoute: typeof MarketplacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms': {
      id: '/wms'
      path: '/wms'
      fullPath: '/wms'
      preLoaderRoute: typeof WmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bitrix-lead': {
      id: '/api/bitrix-lead'
      path: '/api/bitrix-lead'
      fullPath: '/api/bitrix-lead'
      preLoaderRoute: typeof ApiBitrixLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactsRoute: ContactsRoute,
  EcommerceRoute: EcommerceRoute,
  FaqRoute: FaqRoute,
  KgtRoute: KgtRoute,
  MarketplacesRoute: MarketplacesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  ThankYouRoute: ThankYouRoute,
  WmsRoute: WmsRoute,
  ApiBitrixLeadRoute: ApiBitrixLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
